//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.29.0
//! sqlc-gen-rust version: v0.1.10

use tokio_postgres::types::ToSql;
#[derive(Debug, Clone, Copy, postgres_types::ToSql, postgres_types::FromSql)]
#[postgres(name = "tasuki_job_status")]
pub enum TasukiJobStatus {
    #[postgres(name = "pending")]
    Pending,
    #[postgres(name = "running")]
    Running,
    #[postgres(name = "completed")]
    Completed,
    #[postgres(name = "failed")]
    Failed,
    #[postgres(name = "canceled")]
    Canceled,
}
pub struct GetAvailableJobsRow {
    pub id: uuid::Uuid,
    pub job_data: serde_json::Value,
    pub lease_token: uuid::Uuid,
}
impl GetAvailableJobsRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            job_data: row.try_get(1)?,
            lease_token: row.try_get(2)?,
        })
    }
}
pub struct GetAvailableJobs<'a> {
    lease_interval: crate::PgInterval,
    queue_name: &'a str,
    batch_size: i32,
}
impl<'a> GetAvailableJobs<'a> {
    pub const QUERY: &'static str = r"UPDATE 
  tasuki_job j
SET
  status = 'running'::tasuki_job_status,
  attempts = j.attempts + 1,
  lease_expires_at = clock_timestamp() + $1::INTERVAL,
  lease_token = gen_random_uuid()
WHERE 
  id in (
    SELECT 
      id 
    FROM
      tasuki_job
    WHERE 
      (
        (status = 'pending')
        OR
        (status = 'running' AND lease_expires_at IS NOT NULL AND lease_expires_at <= NOW())
      )
      AND 
      (scheduled_at <= NOW() AND attempts < max_attempts AND queue_name = $2::TEXT)
    ORDER BY scheduled_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT $3
  )
RETURNING j.id, j.job_data, j.lease_token::UUID AS lease_token";
    pub async fn query_many(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<Vec<GetAvailableJobsRow>, tokio_postgres::Error> {
        let rows = client
            .query(
                Self::QUERY,
                &[&self.lease_interval, &self.queue_name, &self.batch_size],
            )
            .await?;
        rows.into_iter()
            .map(|r| GetAvailableJobsRow::from_row(&r))
            .collect()
    }
    pub async fn query_stream(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
        let st = client
            .query_raw(Self::QUERY, self.as_slice().into_iter())
            .await?;
        Ok(st)
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 3] {
        [&self.lease_interval, &self.queue_name, &self.batch_size]
    }
}
impl<'a> GetAvailableJobs<'a> {
    pub const fn builder() -> GetAvailableJobsBuilder<'a, ((), (), ())> {
        GetAvailableJobsBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAvailableJobsBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, QueueName, BatchSize> GetAvailableJobsBuilder<'a, ((), QueueName, BatchSize)> {
    pub fn lease_interval(
        self,
        lease_interval: crate::PgInterval,
    ) -> GetAvailableJobsBuilder<'a, (crate::PgInterval, QueueName, BatchSize)> {
        let ((), queue_name, batch_size) = self.fields;
        let _phantom = self._phantom;
        GetAvailableJobsBuilder {
            fields: (lease_interval, queue_name, batch_size),
            _phantom,
        }
    }
}
impl<'a, LeaseInterval, BatchSize> GetAvailableJobsBuilder<'a, (LeaseInterval, (), BatchSize)> {
    pub fn queue_name(
        self,
        queue_name: &'a str,
    ) -> GetAvailableJobsBuilder<'a, (LeaseInterval, &'a str, BatchSize)> {
        let (lease_interval, (), batch_size) = self.fields;
        let _phantom = self._phantom;
        GetAvailableJobsBuilder {
            fields: (lease_interval, queue_name, batch_size),
            _phantom,
        }
    }
}
impl<'a, LeaseInterval, QueueName> GetAvailableJobsBuilder<'a, (LeaseInterval, QueueName, ())> {
    pub fn batch_size(
        self,
        batch_size: i32,
    ) -> GetAvailableJobsBuilder<'a, (LeaseInterval, QueueName, i32)> {
        let (lease_interval, queue_name, ()) = self.fields;
        let _phantom = self._phantom;
        GetAvailableJobsBuilder {
            fields: (lease_interval, queue_name, batch_size),
            _phantom,
        }
    }
}
impl<'a> GetAvailableJobsBuilder<'a, (crate::PgInterval, &'a str, i32)> {
    pub const fn build(self) -> GetAvailableJobs<'a> {
        let (lease_interval, queue_name, batch_size) = self.fields;
        GetAvailableJobs {
            lease_interval,
            queue_name,
            batch_size,
        }
    }
}
pub struct HeartBeatJobRow {
    pub status: TasukiJobStatus,
}
impl HeartBeatJobRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            status: row.try_get(0)?,
        })
    }
}
pub struct HeartBeatJob {
    lease_interval: crate::PgInterval,
    id: uuid::Uuid,
    lease_token: Option<uuid::Uuid>,
}
impl HeartBeatJob {
    pub const QUERY: &'static str = r"UPDATE 
  tasuki_job j
SET
  lease_expires_at = CASE
    WHEN j.status = 'running'::tasuki_job_status
      THEN clock_timestamp() + $1::INTERVAL
    ELSE j.lease_expires_at
  END
WHERE
  id = $2
  AND lease_token = $3
RETURNING j.status";
    pub async fn query_one(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<HeartBeatJobRow, tokio_postgres::Error> {
        let row = client.query_one(Self::QUERY, &self.as_slice()).await?;
        HeartBeatJobRow::from_row(&row)
    }
    pub async fn query_opt(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<Option<HeartBeatJobRow>, tokio_postgres::Error> {
        let row = client.query_opt(Self::QUERY, &self.as_slice()).await?;
        match row {
            Some(row) => Ok(Some(HeartBeatJobRow::from_row(&row)?)),
            None => Ok(None),
        }
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 3] {
        [&self.lease_interval, &self.id, &self.lease_token]
    }
}
impl HeartBeatJob {
    pub const fn builder() -> HeartBeatJobBuilder<'static, ((), (), ())> {
        HeartBeatJobBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct HeartBeatJobBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Id, LeaseToken> HeartBeatJobBuilder<'a, ((), Id, LeaseToken)> {
    pub fn lease_interval(
        self,
        lease_interval: crate::PgInterval,
    ) -> HeartBeatJobBuilder<'a, (crate::PgInterval, Id, LeaseToken)> {
        let ((), id, lease_token) = self.fields;
        let _phantom = self._phantom;
        HeartBeatJobBuilder {
            fields: (lease_interval, id, lease_token),
            _phantom,
        }
    }
}
impl<'a, LeaseInterval, LeaseToken> HeartBeatJobBuilder<'a, (LeaseInterval, (), LeaseToken)> {
    pub fn id(
        self,
        id: uuid::Uuid,
    ) -> HeartBeatJobBuilder<'a, (LeaseInterval, uuid::Uuid, LeaseToken)> {
        let (lease_interval, (), lease_token) = self.fields;
        let _phantom = self._phantom;
        HeartBeatJobBuilder {
            fields: (lease_interval, id, lease_token),
            _phantom,
        }
    }
}
impl<'a, LeaseInterval, Id> HeartBeatJobBuilder<'a, (LeaseInterval, Id, ())> {
    pub fn lease_token(
        self,
        lease_token: Option<uuid::Uuid>,
    ) -> HeartBeatJobBuilder<'a, (LeaseInterval, Id, Option<uuid::Uuid>)> {
        let (lease_interval, id, ()) = self.fields;
        let _phantom = self._phantom;
        HeartBeatJobBuilder {
            fields: (lease_interval, id, lease_token),
            _phantom,
        }
    }
}
impl<'a> HeartBeatJobBuilder<'a, (crate::PgInterval, uuid::Uuid, Option<uuid::Uuid>)> {
    pub const fn build(self) -> HeartBeatJob {
        let (lease_interval, id, lease_token) = self.fields;
        HeartBeatJob {
            lease_interval,
            id,
            lease_token,
        }
    }
}
pub struct CompleteJobRow {}
impl CompleteJobRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct CompleteJob {
    id: uuid::Uuid,
    lease_token: Option<uuid::Uuid>,
}
impl CompleteJob {
    pub const QUERY: &'static str = r"UPDATE 
  tasuki_job j
SET 
  status = 'completed'::tasuki_job_status
WHERE
  id = $1
  AND lease_token = $2";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 2] {
        [&self.id, &self.lease_token]
    }
}
impl CompleteJob {
    pub const fn builder() -> CompleteJobBuilder<'static, ((), ())> {
        CompleteJobBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct CompleteJobBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, LeaseToken> CompleteJobBuilder<'a, ((), LeaseToken)> {
    pub fn id(self, id: uuid::Uuid) -> CompleteJobBuilder<'a, (uuid::Uuid, LeaseToken)> {
        let ((), lease_token) = self.fields;
        let _phantom = self._phantom;
        CompleteJobBuilder {
            fields: (id, lease_token),
            _phantom,
        }
    }
}
impl<'a, Id> CompleteJobBuilder<'a, (Id, ())> {
    pub fn lease_token(
        self,
        lease_token: Option<uuid::Uuid>,
    ) -> CompleteJobBuilder<'a, (Id, Option<uuid::Uuid>)> {
        let (id, ()) = self.fields;
        let _phantom = self._phantom;
        CompleteJobBuilder {
            fields: (id, lease_token),
            _phantom,
        }
    }
}
impl<'a> CompleteJobBuilder<'a, (uuid::Uuid, Option<uuid::Uuid>)> {
    pub const fn build(self) -> CompleteJob {
        let (id, lease_token) = self.fields;
        CompleteJob { id, lease_token }
    }
}
pub struct CancelJobRow {}
impl CancelJobRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct CancelJob {
    id: uuid::Uuid,
    lease_token: Option<uuid::Uuid>,
}
impl CancelJob {
    pub const QUERY: &'static str = r"UPDATE
  tasuki_job j
SET
  status = 'canceled'::tasuki_job_status
WHERE
  id = $1
  AND lease_token = $2";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 2] {
        [&self.id, &self.lease_token]
    }
}
impl CancelJob {
    pub const fn builder() -> CancelJobBuilder<'static, ((), ())> {
        CancelJobBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct CancelJobBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, LeaseToken> CancelJobBuilder<'a, ((), LeaseToken)> {
    pub fn id(self, id: uuid::Uuid) -> CancelJobBuilder<'a, (uuid::Uuid, LeaseToken)> {
        let ((), lease_token) = self.fields;
        let _phantom = self._phantom;
        CancelJobBuilder {
            fields: (id, lease_token),
            _phantom,
        }
    }
}
impl<'a, Id> CancelJobBuilder<'a, (Id, ())> {
    pub fn lease_token(
        self,
        lease_token: Option<uuid::Uuid>,
    ) -> CancelJobBuilder<'a, (Id, Option<uuid::Uuid>)> {
        let (id, ()) = self.fields;
        let _phantom = self._phantom;
        CancelJobBuilder {
            fields: (id, lease_token),
            _phantom,
        }
    }
}
impl<'a> CancelJobBuilder<'a, (uuid::Uuid, Option<uuid::Uuid>)> {
    pub const fn build(self) -> CancelJob {
        let (id, lease_token) = self.fields;
        CancelJob { id, lease_token }
    }
}
pub struct RetryJobRow {}
impl RetryJobRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct RetryJob {
    interval: Option<crate::PgInterval>,
    id: uuid::Uuid,
    lease_token: Option<uuid::Uuid>,
}
impl RetryJob {
    pub const QUERY: &'static str = r"UPDATE tasuki_job j
SET 
  status = CASE 
            WHEN j.attempts < j.max_attempts THEN 'pending'::tasuki_job_status
            ELSE 'failed'::tasuki_job_status
           END,
  scheduled_at = CASE
                  WHEN j.attempts < j.max_attempts 
                    THEN clock_timestamp() + coalesce(
                      $1,
                      make_interval(secs := power(j.attempts, 4.0) * (0.9 + random() * 0.2))
                      )::INTERVAL
                  ELSE scheduled_at
                 END,
  lease_expires_at = NULL
WHERE 
  id = $2
  AND lease_token = $3";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 3] {
        [&self.interval, &self.id, &self.lease_token]
    }
}
impl RetryJob {
    pub const fn builder() -> RetryJobBuilder<'static, ((), (), ())> {
        RetryJobBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct RetryJobBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Id, LeaseToken> RetryJobBuilder<'a, ((), Id, LeaseToken)> {
    pub fn interval(
        self,
        interval: Option<crate::PgInterval>,
    ) -> RetryJobBuilder<'a, (Option<crate::PgInterval>, Id, LeaseToken)> {
        let ((), id, lease_token) = self.fields;
        let _phantom = self._phantom;
        RetryJobBuilder {
            fields: (interval, id, lease_token),
            _phantom,
        }
    }
}
impl<'a, Interval, LeaseToken> RetryJobBuilder<'a, (Interval, (), LeaseToken)> {
    pub fn id(self, id: uuid::Uuid) -> RetryJobBuilder<'a, (Interval, uuid::Uuid, LeaseToken)> {
        let (interval, (), lease_token) = self.fields;
        let _phantom = self._phantom;
        RetryJobBuilder {
            fields: (interval, id, lease_token),
            _phantom,
        }
    }
}
impl<'a, Interval, Id> RetryJobBuilder<'a, (Interval, Id, ())> {
    pub fn lease_token(
        self,
        lease_token: Option<uuid::Uuid>,
    ) -> RetryJobBuilder<'a, (Interval, Id, Option<uuid::Uuid>)> {
        let (interval, id, ()) = self.fields;
        let _phantom = self._phantom;
        RetryJobBuilder {
            fields: (interval, id, lease_token),
            _phantom,
        }
    }
}
impl<'a> RetryJobBuilder<'a, (Option<crate::PgInterval>, uuid::Uuid, Option<uuid::Uuid>)> {
    pub const fn build(self) -> RetryJob {
        let (interval, id, lease_token) = self.fields;
        RetryJob {
            interval,
            id,
            lease_token,
        }
    }
}
pub struct InsertJobOneRow {}
impl InsertJobOneRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct InsertJobOne<'a> {
    max_attempts: i32,
    job_data: &'a serde_json::Value,
    queue_name: &'a str,
    interval: crate::PgInterval,
}
impl<'a> InsertJobOne<'a> {
    pub const QUERY: &'static str = r"INSERT INTO
  tasuki_job
  (max_attempts, job_data, queue_name, scheduled_at)
VALUES
  ($1, $2, $3, clock_timestamp() + $4::INTERVAL)";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 4] {
        [
            &self.max_attempts,
            &self.job_data,
            &self.queue_name,
            &self.interval,
        ]
    }
}
impl<'a> InsertJobOne<'a> {
    pub const fn builder() -> InsertJobOneBuilder<'a, ((), (), (), ())> {
        InsertJobOneBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct InsertJobOneBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, JobData, QueueName, Interval> InsertJobOneBuilder<'a, ((), JobData, QueueName, Interval)> {
    pub fn max_attempts(
        self,
        max_attempts: i32,
    ) -> InsertJobOneBuilder<'a, (i32, JobData, QueueName, Interval)> {
        let ((), job_data, queue_name, interval) = self.fields;
        let _phantom = self._phantom;
        InsertJobOneBuilder {
            fields: (max_attempts, job_data, queue_name, interval),
            _phantom,
        }
    }
}
impl<'a, MaxAttempts, QueueName, Interval>
    InsertJobOneBuilder<'a, (MaxAttempts, (), QueueName, Interval)>
{
    pub fn job_data(
        self,
        job_data: &'a serde_json::Value,
    ) -> InsertJobOneBuilder<'a, (MaxAttempts, &'a serde_json::Value, QueueName, Interval)> {
        let (max_attempts, (), queue_name, interval) = self.fields;
        let _phantom = self._phantom;
        InsertJobOneBuilder {
            fields: (max_attempts, job_data, queue_name, interval),
            _phantom,
        }
    }
}
impl<'a, MaxAttempts, JobData, Interval>
    InsertJobOneBuilder<'a, (MaxAttempts, JobData, (), Interval)>
{
    pub fn queue_name(
        self,
        queue_name: &'a str,
    ) -> InsertJobOneBuilder<'a, (MaxAttempts, JobData, &'a str, Interval)> {
        let (max_attempts, job_data, (), interval) = self.fields;
        let _phantom = self._phantom;
        InsertJobOneBuilder {
            fields: (max_attempts, job_data, queue_name, interval),
            _phantom,
        }
    }
}
impl<'a, MaxAttempts, JobData, QueueName>
    InsertJobOneBuilder<'a, (MaxAttempts, JobData, QueueName, ())>
{
    pub fn interval(
        self,
        interval: crate::PgInterval,
    ) -> InsertJobOneBuilder<'a, (MaxAttempts, JobData, QueueName, crate::PgInterval)> {
        let (max_attempts, job_data, queue_name, ()) = self.fields;
        let _phantom = self._phantom;
        InsertJobOneBuilder {
            fields: (max_attempts, job_data, queue_name, interval),
            _phantom,
        }
    }
}
impl<'a> InsertJobOneBuilder<'a, (i32, &'a serde_json::Value, &'a str, crate::PgInterval)> {
    pub const fn build(self) -> InsertJobOne<'a> {
        let (max_attempts, job_data, queue_name, interval) = self.fields;
        InsertJobOne {
            max_attempts,
            job_data,
            queue_name,
            interval,
        }
    }
}
pub struct InsertJobManyRow {}
impl InsertJobManyRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct InsertJobMany<'a> {
    max_attempts: i32,
    job_data: &'a serde_json::Value,
    queue_name: &'a str,
    scheduled_at: &'a std::time::SystemTime,
}
impl<'a> InsertJobMany<'a> {
    pub const QUERY: &'static str = r"COPY tasuki_job (max_attempts,job_data,queue_name,scheduled_at) FROM STDIN (FORMAT BINARY)";
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 4] {
        [
            &self.max_attempts,
            &self.job_data,
            &self.queue_name,
            &self.scheduled_at,
        ]
    }
}
impl<'a> InsertJobMany<'a> {
    pub const fn builder() -> InsertJobManyBuilder<'a, ((), (), (), ())> {
        InsertJobManyBuilder {
            fields: ((), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct InsertJobManyBuilder<'a, Fields = ((), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, JobData, QueueName, ScheduledAt>
    InsertJobManyBuilder<'a, ((), JobData, QueueName, ScheduledAt)>
{
    pub fn max_attempts(
        self,
        max_attempts: i32,
    ) -> InsertJobManyBuilder<'a, (i32, JobData, QueueName, ScheduledAt)> {
        let ((), job_data, queue_name, scheduled_at) = self.fields;
        let _phantom = self._phantom;
        InsertJobManyBuilder {
            fields: (max_attempts, job_data, queue_name, scheduled_at),
            _phantom,
        }
    }
}
impl<'a, MaxAttempts, QueueName, ScheduledAt>
    InsertJobManyBuilder<'a, (MaxAttempts, (), QueueName, ScheduledAt)>
{
    pub fn job_data(
        self,
        job_data: &'a serde_json::Value,
    ) -> InsertJobManyBuilder<'a, (MaxAttempts, &'a serde_json::Value, QueueName, ScheduledAt)>
    {
        let (max_attempts, (), queue_name, scheduled_at) = self.fields;
        let _phantom = self._phantom;
        InsertJobManyBuilder {
            fields: (max_attempts, job_data, queue_name, scheduled_at),
            _phantom,
        }
    }
}
impl<'a, MaxAttempts, JobData, ScheduledAt>
    InsertJobManyBuilder<'a, (MaxAttempts, JobData, (), ScheduledAt)>
{
    pub fn queue_name(
        self,
        queue_name: &'a str,
    ) -> InsertJobManyBuilder<'a, (MaxAttempts, JobData, &'a str, ScheduledAt)> {
        let (max_attempts, job_data, (), scheduled_at) = self.fields;
        let _phantom = self._phantom;
        InsertJobManyBuilder {
            fields: (max_attempts, job_data, queue_name, scheduled_at),
            _phantom,
        }
    }
}
impl<'a, MaxAttempts, JobData, QueueName>
    InsertJobManyBuilder<'a, (MaxAttempts, JobData, QueueName, ())>
{
    pub fn scheduled_at(
        self,
        scheduled_at: &'a std::time::SystemTime,
    ) -> InsertJobManyBuilder<'a, (MaxAttempts, JobData, QueueName, &'a std::time::SystemTime)>
    {
        let (max_attempts, job_data, queue_name, ()) = self.fields;
        let _phantom = self._phantom;
        InsertJobManyBuilder {
            fields: (max_attempts, job_data, queue_name, scheduled_at),
            _phantom,
        }
    }
}
impl<'a>
    InsertJobManyBuilder<
        'a,
        (
            i32,
            &'a serde_json::Value,
            &'a str,
            &'a std::time::SystemTime,
        ),
    >
{
    pub const fn build(self) -> InsertJobMany<'a> {
        let (max_attempts, job_data, queue_name, scheduled_at) = self.fields;
        InsertJobMany {
            max_attempts,
            job_data,
            queue_name,
            scheduled_at,
        }
    }
}
pub struct AddJobNotifyRow {
    pub pg_notify: crate::PgVoid,
}
impl AddJobNotifyRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            pg_notify: row.try_get(0)?,
        })
    }
}
pub struct AddJobNotify<'a> {
    channel_name: &'a str,
    queue_name: &'a str,
}
impl<'a> AddJobNotify<'a> {
    pub const QUERY: &'static str = r"SELECT pg_notify(
  $1::TEXT,
  json_build_object('q', $2::TEXT)::TEXT
)";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 2] {
        [&self.channel_name, &self.queue_name]
    }
}
impl<'a> AddJobNotify<'a> {
    pub const fn builder() -> AddJobNotifyBuilder<'a, ((), ())> {
        AddJobNotifyBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct AddJobNotifyBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, QueueName> AddJobNotifyBuilder<'a, ((), QueueName)> {
    pub fn channel_name(
        self,
        channel_name: &'a str,
    ) -> AddJobNotifyBuilder<'a, (&'a str, QueueName)> {
        let ((), queue_name) = self.fields;
        let _phantom = self._phantom;
        AddJobNotifyBuilder {
            fields: (channel_name, queue_name),
            _phantom,
        }
    }
}
impl<'a, ChannelName> AddJobNotifyBuilder<'a, (ChannelName, ())> {
    pub fn queue_name(
        self,
        queue_name: &'a str,
    ) -> AddJobNotifyBuilder<'a, (ChannelName, &'a str)> {
        let (channel_name, ()) = self.fields;
        let _phantom = self._phantom;
        AddJobNotifyBuilder {
            fields: (channel_name, queue_name),
            _phantom,
        }
    }
}
impl<'a> AddJobNotifyBuilder<'a, (&'a str, &'a str)> {
    pub const fn build(self) -> AddJobNotify<'a> {
        let (channel_name, queue_name) = self.fields;
        AddJobNotify {
            channel_name,
            queue_name,
        }
    }
}
pub struct CancelJobByIdRow {}
impl CancelJobByIdRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct CancelJobById {
    id: uuid::Uuid,
}
impl CancelJobById {
    pub const QUERY: &'static str = r"UPDATE
  tasuki_job j
SET 
  status = 'canceled'::tasuki_job_status
WHERE
  id = $1";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 1] {
        [&self.id]
    }
}
impl CancelJobById {
    pub const fn builder() -> CancelJobByIdBuilder<'static, ((),)> {
        CancelJobByIdBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct CancelJobByIdBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> CancelJobByIdBuilder<'a, ((),)> {
    pub fn id(self, id: uuid::Uuid) -> CancelJobByIdBuilder<'a, (uuid::Uuid,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        CancelJobByIdBuilder {
            fields: (id,),
            _phantom,
        }
    }
}
impl<'a> CancelJobByIdBuilder<'a, (uuid::Uuid,)> {
    pub const fn build(self) -> CancelJobById {
        let (id,) = self.fields;
        CancelJobById { id }
    }
}
pub struct RetryFailedByQueueRow {}
impl RetryFailedByQueueRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {})
    }
}
pub struct RetryFailedByQueue<'a> {
    queue_name: &'a str,
}
impl<'a> RetryFailedByQueue<'a> {
    pub const QUERY: &'static str = r"UPDATE tasuki_job j
SET
  status = 'pending'::tasuki_job_status,
  attempts = 0,
  scheduled_at = clock_timestamp(),
  lease_expires_at = NULL
WHERE
  j.status = 'failed'::tasuki_job_status
  AND j.attempts < j.max_attempts
  AND j.queue_name = $1::TEXT";
    pub async fn execute(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<u64, tokio_postgres::Error> {
        client.execute(Self::QUERY, &self.as_slice()).await
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 1] {
        [&self.queue_name]
    }
}
impl<'a> RetryFailedByQueue<'a> {
    pub const fn builder() -> RetryFailedByQueueBuilder<'a, ((),)> {
        RetryFailedByQueueBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct RetryFailedByQueueBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> RetryFailedByQueueBuilder<'a, ((),)> {
    pub fn queue_name(self, queue_name: &'a str) -> RetryFailedByQueueBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        RetryFailedByQueueBuilder {
            fields: (queue_name,),
            _phantom,
        }
    }
}
impl<'a> RetryFailedByQueueBuilder<'a, (&'a str,)> {
    pub const fn build(self) -> RetryFailedByQueue<'a> {
        let (queue_name,) = self.fields;
        RetryFailedByQueue { queue_name }
    }
}
pub struct AggregateQueueStatRow {
    pub pending: i64,
    pub running: i64,
    pub completed: i64,
    pub failed: i64,
    pub canceled: i64,
}
impl AggregateQueueStatRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            pending: row.try_get(0)?,
            running: row.try_get(1)?,
            completed: row.try_get(2)?,
            failed: row.try_get(3)?,
            canceled: row.try_get(4)?,
        })
    }
}
pub struct AggregateQueueStat<'a> {
    queue_name: &'a str,
}
impl<'a> AggregateQueueStat<'a> {
    pub const QUERY: &'static str = r"SELECT 
  SUM(
    CASE WHEN status = 'pending'
      THEN 1
      ELSE 0
    END
  ) AS pending,
  SUM(
    CASE WHEN status = 'running'
      THEN 1
      ELSE 0
    END
  ) AS running,
  SUM(
    CASE WHEN status = 'completed'
      THEN 1
      ELSE 0
    END
  ) AS completed,
  SUM(
    CASE WHEN status = 'failed'
      THEN 1
      ELSE 0
    END
  ) AS failed,
  SUM(
    CASE WHEN status = 'canceled'
      THEN 1
      ELSE 0
    END
  ) AS canceled
FROM 
  tasuki_job
WHERE 
  queue_name = $1";
    pub async fn query_one(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<AggregateQueueStatRow, tokio_postgres::Error> {
        let row = client.query_one(Self::QUERY, &self.as_slice()).await?;
        AggregateQueueStatRow::from_row(&row)
    }
    pub async fn query_opt(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<Option<AggregateQueueStatRow>, tokio_postgres::Error> {
        let row = client.query_opt(Self::QUERY, &self.as_slice()).await?;
        match row {
            Some(row) => Ok(Some(AggregateQueueStatRow::from_row(&row)?)),
            None => Ok(None),
        }
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 1] {
        [&self.queue_name]
    }
}
impl<'a> AggregateQueueStat<'a> {
    pub const fn builder() -> AggregateQueueStatBuilder<'a, ((),)> {
        AggregateQueueStatBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct AggregateQueueStatBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> AggregateQueueStatBuilder<'a, ((),)> {
    pub fn queue_name(self, queue_name: &'a str) -> AggregateQueueStatBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        AggregateQueueStatBuilder {
            fields: (queue_name,),
            _phantom,
        }
    }
}
impl<'a> AggregateQueueStatBuilder<'a, (&'a str,)> {
    pub const fn build(self) -> AggregateQueueStat<'a> {
        let (queue_name,) = self.fields;
        AggregateQueueStat { queue_name }
    }
}
pub struct CleanJobsRow {
    pub id: uuid::Uuid,
}
impl CleanJobsRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
        })
    }
}
pub struct CleanJobs<'a> {
    job_status: TasukiJobStatus,
    queue_name: &'a str,
}
impl<'a> CleanJobs<'a> {
    pub const QUERY: &'static str = r"DELETE FROM
  tasuki_job
WHERE 
  status = $1
  AND queue_name = $2
RETURNING id";
    pub async fn query_many(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<Vec<CleanJobsRow>, tokio_postgres::Error> {
        let rows = client
            .query(Self::QUERY, &[&self.job_status, &self.queue_name])
            .await?;
        rows.into_iter()
            .map(|r| CleanJobsRow::from_row(&r))
            .collect()
    }
    pub async fn query_stream(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
        let st = client
            .query_raw(Self::QUERY, self.as_slice().into_iter())
            .await?;
        Ok(st)
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 2] {
        [&self.job_status, &self.queue_name]
    }
}
impl<'a> CleanJobs<'a> {
    pub const fn builder() -> CleanJobsBuilder<'a, ((), ())> {
        CleanJobsBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct CleanJobsBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, QueueName> CleanJobsBuilder<'a, ((), QueueName)> {
    pub fn job_status(
        self,
        job_status: TasukiJobStatus,
    ) -> CleanJobsBuilder<'a, (TasukiJobStatus, QueueName)> {
        let ((), queue_name) = self.fields;
        let _phantom = self._phantom;
        CleanJobsBuilder {
            fields: (job_status, queue_name),
            _phantom,
        }
    }
}
impl<'a, JobStatus> CleanJobsBuilder<'a, (JobStatus, ())> {
    pub fn queue_name(self, queue_name: &'a str) -> CleanJobsBuilder<'a, (JobStatus, &'a str)> {
        let (job_status, ()) = self.fields;
        let _phantom = self._phantom;
        CleanJobsBuilder {
            fields: (job_status, queue_name),
            _phantom,
        }
    }
}
impl<'a> CleanJobsBuilder<'a, (TasukiJobStatus, &'a str)> {
    pub const fn build(self) -> CleanJobs<'a> {
        let (job_status, queue_name) = self.fields;
        CleanJobs {
            job_status,
            queue_name,
        }
    }
}
pub struct ListJobsRow {
    pub id: uuid::Uuid,
    pub status: TasukiJobStatus,
}
impl ListJobsRow {
    pub fn from_row(row: &tokio_postgres::Row) -> Result<Self, tokio_postgres::Error> {
        Ok(Self {
            id: row.try_get(0)?,
            status: row.try_get(1)?,
        })
    }
}
pub struct ListJobs<'a> {
    cursor_job_id: Option<uuid::Uuid>,
    queue_name: Option<&'a str>,
    page_size: i32,
}
impl<'a> ListJobs<'a> {
    pub const QUERY: &'static str = r"SELECT
  j.id,
  j.status
FROM
  tasuki_job j
WHERE
  j.created_at < CASE 
    WHEN $1::UUID IS NOT NULL
      THEN (
        SELECT 
          created_at
        FROM 
          tasuki_job jj
        WHERE
          jj.id = $1::UUID
          AND jj.queue_name = $2
        )
    ELSE (
        SELECT
          MAX(created_at)
        FROM
          tasuki_job jj
        WHERE
          jj.queue_name = $2
        LIMIT 1
        )
  END
  AND j.queue_name = $2
ORDER BY j.created_at DESC, j.id DESC
LIMIT $3";
    pub async fn query_many(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<Vec<ListJobsRow>, tokio_postgres::Error> {
        let rows = client
            .query(
                Self::QUERY,
                &[&self.cursor_job_id, &self.queue_name, &self.page_size],
            )
            .await?;
        rows.into_iter()
            .map(|r| ListJobsRow::from_row(&r))
            .collect()
    }
    pub async fn query_stream(
        &self,
        client: &impl tokio_postgres::GenericClient,
    ) -> Result<tokio_postgres::RowStream, tokio_postgres::Error> {
        let st = client
            .query_raw(Self::QUERY, self.as_slice().into_iter())
            .await?;
        Ok(st)
    }
    pub fn as_slice(&self) -> [&(dyn ToSql + Sync); 3] {
        [&self.cursor_job_id, &self.queue_name, &self.page_size]
    }
}
impl<'a> ListJobs<'a> {
    pub const fn builder() -> ListJobsBuilder<'a, ((), (), ())> {
        ListJobsBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListJobsBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, QueueName, PageSize> ListJobsBuilder<'a, ((), QueueName, PageSize)> {
    pub fn cursor_job_id(
        self,
        cursor_job_id: Option<uuid::Uuid>,
    ) -> ListJobsBuilder<'a, (Option<uuid::Uuid>, QueueName, PageSize)> {
        let ((), queue_name, page_size) = self.fields;
        let _phantom = self._phantom;
        ListJobsBuilder {
            fields: (cursor_job_id, queue_name, page_size),
            _phantom,
        }
    }
}
impl<'a, CursorJobId, PageSize> ListJobsBuilder<'a, (CursorJobId, (), PageSize)> {
    pub fn queue_name(
        self,
        queue_name: Option<&'a str>,
    ) -> ListJobsBuilder<'a, (CursorJobId, Option<&'a str>, PageSize)> {
        let (cursor_job_id, (), page_size) = self.fields;
        let _phantom = self._phantom;
        ListJobsBuilder {
            fields: (cursor_job_id, queue_name, page_size),
            _phantom,
        }
    }
}
impl<'a, CursorJobId, QueueName> ListJobsBuilder<'a, (CursorJobId, QueueName, ())> {
    pub fn page_size(self, page_size: i32) -> ListJobsBuilder<'a, (CursorJobId, QueueName, i32)> {
        let (cursor_job_id, queue_name, ()) = self.fields;
        let _phantom = self._phantom;
        ListJobsBuilder {
            fields: (cursor_job_id, queue_name, page_size),
            _phantom,
        }
    }
}
impl<'a> ListJobsBuilder<'a, (Option<uuid::Uuid>, Option<&'a str>, i32)> {
    pub const fn build(self) -> ListJobs<'a> {
        let (cursor_job_id, queue_name, page_size) = self.fields;
        ListJobs {
            cursor_job_id,
            queue_name,
            page_size,
        }
    }
}
