[package]
name = "tasuki"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "uuid"] }
serde = "1.0"
serde_json = "1.0"

futures = "0.3"
futures-timer = "3.0"
pin-project-lite = "0.2"

tracing = "0.1"
tracing-subscriber = "0.3"


[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tokio-util = "0.7"