services:
  dev:
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
      - codex-auth:/home/vscode/.codex
  postgres:
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

volumes:
  codex-auth: